name: Publish Python Package

on:
  push:
    tags:
      - 'v*'   # triggers on version tags like v0.1.0

# Tag your releases with 'v' prefix to trigger this workflow
# This workflow builds and publishes the package to PyPI when a new version is tagged.
# Example command to create a tag:
# git tag v0.1.0
# git push origin v0.1.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
